"""
agents/plan_execute_agent.py

Plan-Execute Agent — Plan ALL steps first, then execute them one by one.

Flow:
    Query → Planner LLM → [Step1, Step2, Step3, ...]
                                ↓
                         Executor LLM → runs Step1 → result
                                     → runs Step2 → result
                                     → runs Step3 → result
                                ↓
                         Synthesizer LLM → combines results → Final Answer

Key difference vs ReAct:
- ReAct  → decides next action AFTER seeing each tool result (reactive)
- Plan-Execute → commits to a full plan BEFORE any tool is called (proactive)

ReAct is better when: the next step depends on previous results
Plan-Execute is better when: all steps are known in advance
"""

from typing import Optional, TypedDict, Annotated
import operator
from loguru import logger

from agents.base_agent import BaseAgent, AgentResult
from config.settings import settings


# ── LangGraph State ────────────────────────────────────────────────────────────
class PlanExecuteState(TypedDict):
    query: str
    plan: list[str]                              # Steps generated by planner
    completed_steps: Annotated[list, operator.add]  # Results appended as steps complete
    final_answer: str


# ── Prompts ────────────────────────────────────────────────────────────────────
PLANNER_PROMPT = """You are a task planner. Given a user query, break it into 2-4 clear, 
executable steps. Each step should be a single action (search, calculate, execute code, etc).

Output ONLY a numbered list. No preamble, no explanation.
Example:
1. Search the web for the current GDP of the USA
2. Calculate what percentage $X is of $105 trillion world GDP

Query: {query}
Steps:"""

EXECUTOR_PROMPT = """You are a task executor with access to these tools:
- web_search: search the web for real-time information  
- code_executor: run Python code in a sandbox
- vision_analyzer: analyze images (provide URL + question)
- calculator: evaluate math expressions
- wikipedia_search: look up encyclopedic knowledge

Execute ONLY this specific step. Use exactly ONE tool call.
Step to execute: {step}

Context from previous steps:
{context}
"""

SYNTHESIZER_PROMPT = """You are a result synthesizer. Given a user query and the results 
from executing each step of a plan, write a clear, concise final answer.

Original query: {query}

Plan steps and their results:
{step_results}

Write the final answer:"""


class PlanExecuteAgent(BaseAgent):
    """
    Plan-Execute agent using a custom LangGraph state machine.

    Nodes:
        planner   → generates the plan (list of steps)
        executor  → executes each step using tools
        synthesizer → combines all results into final answer
    """

    def __init__(self, model_name: str = "llama-70b"):
        super().__init__(model_name)
        logger.info(f"PlanExecuteAgent initialized | model={self.model_id}")

    def _build_graph(self):
        """Build the Plan → Execute → Synthesize state graph."""
        from langgraph.graph import StateGraph, END
        from langgraph.prebuilt import create_react_agent
        from langchain_core.messages import HumanMessage, SystemMessage

        # ── Single-step executor (a mini ReAct agent per step) ────────────────
        step_executor = create_react_agent(
            model=self.llm,
            tools=self.tools,
        )

        def planner_node(state: PlanExecuteState) -> dict:
            """Generate a step-by-step plan for the query."""
            prompt = PLANNER_PROMPT.format(query=state["query"])
            response = self.llm.invoke([HumanMessage(content=prompt)])
            raw_plan = response.content

            # Parse numbered list into steps
            steps = []
            for line in raw_plan.strip().split("\n"):
                line = line.strip()
                if line and (line[0].isdigit() or line.startswith("-")):
                    # Remove leading "1. " or "- "
                    step = line.lstrip("0123456789.-) ").strip()
                    if step:
                        steps.append(step)

            # Fallback: if parsing failed, use the whole response as one step
            if not steps:
                steps = [state["query"]]

            logger.debug(f"[PlanExecute] Plan generated: {steps}")
            return {"plan": steps, "completed_steps": []}

        def executor_node(state: PlanExecuteState) -> dict:
            """Execute the next pending step using tools."""
            completed = len(state["completed_steps"])
            plan = state["plan"]

            if completed >= len(plan):
                return {"completed_steps": []}

            current_step = plan[completed]
            context = "\n".join([
                f"Step {i+1} result: {r}"
                for i, r in enumerate(state["completed_steps"])
            ]) if state["completed_steps"] else "No previous steps."

            prompt = EXECUTOR_PROMPT.format(
                step=current_step,
                context=context
            )

            logger.debug(f"[PlanExecute] Executing step {completed+1}: '{current_step}'")

            result = step_executor.invoke({
                "messages": [HumanMessage(content=prompt)]
            })

            # Extract final answer from executor
            messages = result.get("messages", [])
            step_result = ""
            for msg in reversed(messages):
                if msg.__class__.__name__ == "AIMessage" and msg.content:
                    step_result = msg.content
                    break

            step_summary = f"Step {completed+1} ({current_step[:50]}): {step_result[:300]}"
            return {"completed_steps": [step_summary]}

        def synthesizer_node(state: PlanExecuteState) -> dict:
            """Synthesize all step results into a final answer."""
            step_results = "\n".join(state["completed_steps"])
            prompt = SYNTHESIZER_PROMPT.format(
                query=state["query"],
                step_results=step_results
            )
            response = self.llm.invoke([HumanMessage(content=prompt)])
            return {"final_answer": response.content}

        def should_continue(state: PlanExecuteState) -> str:
            """Route: keep executing if steps remain, else synthesize."""
            completed = len(state["completed_steps"])
            total = len(state["plan"])
            if completed < total:
                return "executor"
            return "synthesizer"

        # ── Build graph ────────────────────────────────────────────────────────
        graph = StateGraph(PlanExecuteState)
        graph.add_node("planner", planner_node)
        graph.add_node("executor", executor_node)
        graph.add_node("synthesizer", synthesizer_node)

        graph.set_entry_point("planner")
        graph.add_edge("planner", "executor")
        graph.add_conditional_edges(
            "executor",
            should_continue,
            {"executor": "executor", "synthesizer": "synthesizer"}
        )
        graph.add_edge("synthesizer", END)

        return graph.compile()

    def run(self, query: str, image_path: Optional[str] = None) -> AgentResult:
        """
        Run Plan-Execute agent on a query.

        Args:
            query: User query
            image_path: Optional image — appended to query

        Returns:
            AgentResult with output, plan, tool usage, latency
        """
        if image_path:
            query = f"{query}\n\nImage: {image_path}"

        logger.info(f"[PlanExecute] Running: '{query[:80]}' | model={self.model_id}")

        try:
            initial_state: PlanExecuteState = {
                "query": query,
                "plan": [],
                "completed_steps": [],
                "final_answer": "",
            }

            def _invoke():
                return self.graph.invoke(
                    initial_state,
                    config={"recursion_limit": 50}
                )

            result, latency_ms = self._timed_run(_invoke)

            plan = result.get("plan", [])
            completed = result.get("completed_steps", [])
            final_answer = result.get("final_answer", "")

            # Estimate tool calls from completed step count
            # (each step uses ~1 tool call via the mini-executor)
            tool_calls_made = [f"step_{i+1}_tool" for i in range(len(completed))]

            logger.info(
                f"[PlanExecute] Done | latency={latency_ms:.0f}ms | "
                f"steps={len(plan)} | completed={len(completed)}"
            )

            return AgentResult(
                output=final_answer or "No answer generated.",
                tool_calls=tool_calls_made,
                tool_call_count=len(completed),
                iterations=len(plan),
                latency_ms=latency_ms,
                success=True,
                plan=plan,
            )

        except Exception as e:
            logger.error(f"[PlanExecute] Error: {e}")
            return AgentResult(
                output=f"Agent error: {str(e)}",
                tool_calls=[],
                tool_call_count=0,
                iterations=0,
                latency_ms=0.0,
                success=False,
                error=str(e),
            )
